### ISSUE TITLE
抖音解密

### ISSUE THREAD

**Issue by chaogewudi** [WXjzcccc/ForensicsTool#1]
抖音的uid 再拼接上那一串，太长了，解密的时候不对

**Comment by WXjzcccc** [comment]
哪里需要拼接？抖音需要-m 0 -t 16先计算密钥，然后-m 1 -t 15对数据库进行解密，全程只需要计算密钥时指定uid，解密数据库时指定密码，不用拼接啊？提issue附截图或者报错信息

**Comment by chaogewudi** [comment]
![111111111111](https://github.com/user-attachments/assets/f786437d-88d2-4b97-908f-dcbafb06c3ae)
点击回车后 控制台没有任何打印

**Comment by chaogewudi** [comment]
![2222222](https://github.com/user-attachments/assets/d0c2d27d-b5fd-429a-8e6e-0484d77617f4)
您好，这个得到的结果就是我一开始说的 把uid 拼接起来得到的秘钥，我用 sqlcipher.exe 工具输入这个秘钥 仍然打不开数据库db

**Comment by WXjzcccc** [comment]
你看`[注意]`，选择wcdb进行解密，而你直接用sqlcipher打开，自然是打不开，wcdb修改了默认加密参数，你应该用-m 1 -t 15 -f 数据库wenjian -p 密码 进行解密，然后可以直接打开解密后的sqlite数据库
