### ISSUE TITLE
小红书db文件

### ISSUE THREAD

**Issue by chaogewudi** [WXjzcccc/ForensicsTool#2]
大佬，是否可以做一个小红书的db读取

**Comment by chaogewudi** [comment]
辛苦大佬了，附件已添加小红书整体备份数据


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WXjzcccc/ForensicsTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月2日(星期一) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WXjzcccc/ForensicsTool] 小红书db文件 (Issue #2)





 
我不使用小红书，你可以给我一份小红书软件的数据包，不论是你自己的数据，亦或是比武、竞赛中的数据
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

com.xingin.xhs.rar (80.59M, 2024年10月02日 17:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=71653361fef5c3ca5f9ee95e1065071f4e11055657530d561b570703044803520e501e550306001d5301515503075105525050073677355359081d195f0b5259584b4b09454b475144650e&code=6e3a6e50

**Comment by WXjzcccc** [comment]
解密密码为通用密码`xhsdev`，选择sqlcipher3解密msgDB文件即可

**Comment by WXjzcccc** [comment]
此issue关闭

**Comment by chaogewudi** [comment]
还得是我大哥

**Comment by bfx21** [comment]
我的小红书db文件也无法打开，需要解密，大佬能帮帮忙吗
