### ISSUE TITLE
ForensicsTool

### ISSUE THREAD

**Issue by Johnluckygogogo** [WXjzcccc/ForensicsTool#4]
大神，我关注你博客园的微博，看到你解题里有使用ForensicsTool workbench这个软件，软件能分享下吗？谢谢。

**Comment by WXjzcccc** [comment]
谁教你这种都能提issue的？

**Comment by Johnluckygogogo** [comment]
> 谁教你这种都能提issue的？
不好意思，在下是个萌新，所以提的要求在你看来有点过分了。

**Comment by WXjzcccc** [comment]
gui.pyw
